run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen

linters:
  enable-all: true
  disable:
    - dupl
    - errcheck
    - gci
    - gochecknoglobals
    - gocognit
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nestif
    - nlreturn
    - noctx
    - testpackage
    - unparam
    - wsl
