language: go
sudo: false
install:
  # hack alert: setting GO111MODULE to off so dep can be go get'ed
  - GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint github.com/golang/dep/cmd/dep
  - if [[ $DEP_TOOL == "dep" ]]; then dep ensure -v; fi
  - if [[ $DEP_TOOL == "mod" ]]; then go mod download; fi
script:
  - if [[ $JOB == "lint" ]]; then golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals -D unparam -D gosec --deadline 5m ./...; fi
  - if [[ $JOB == "gotest" ]]; then go test -race ./...; fi
env:
  matrix:
    - DEP_TOOL=dep GO111MODULE=off JOB=lint
    - DEP_TOOL=dep GO111MODULE=off JOB=gotest
    - DEP_TOOL=mod GO111MODULE=on JOB=lint
    - DEP_TOOL=mod GO111MODULE=on JOB=gotest
go:
  - 1.10.x
  - 1.11.x
  - 1.12beta2
  - tip
matrix:
  fast_finish: true
  exclude:
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on JOB=gotest
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on JOB=lint
