
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.19.0 - 0.39.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1 - 1.7.2"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.2.0 - 0.5.0"

[prune]
  go-tests = true
  unused-packages = true
