
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.19.0 - 0.35.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1 - 1.7.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[prune]
  go-tests = true
  unused-packages = true
