name: docker-tests
on:
  pull_request:
    branches:
      - main
jobs:
  test-root-dockerfile:
    name: test root dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: setup qemu
        uses: docker/setup-qemu-action@v1.2.0

      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          tags: fsouza/fake-gcs-server:latest
          platforms: linux/amd64,linux/arm64
