name: Test Dockerfiles
on:
  pull_request:
    paths:
      - Dockerfile
      - ci/Dockerfile
jobs:
  test-root-dockerfile:
    name: test root dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test Dockerfile
        if: github.event_name == 'pull_request'
        uses: docker://docker
        with:
          entrypoint: docker
          args: build .

  test-ci-dockerfile:
    name: test ci dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        id: go
        with:
          version: 1.13rc1

      - name: go-build
        run: go build -o fake-gcs-server -mod readonly
        env:
          CGO_ENABLED: 0
          GOPROXY: https://proxy.golang.org,https://gocenter.io,direct

      - name: test ci/Dockerfile
        if: github.event_name == 'pull_request'
        uses: docker://docker
        with:
          entrypoint: docker
          args: build -f ci/Dockerfile .
