name: goreleaser-test
on:
  pull_request:
    paths:
      - .goreleaser.yml
jobs:
  test-goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0

      - uses: docker://goreleaser/goreleaser
        with:
          args: release --snapshot -f ci/.goreleaser.yml
