name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - 1.16
          - 1.17
        os:
          - macos
          - ubuntu
          - windows
        arch:
          - 386
          - amd64
        exclude:
          - os: macos
            arch: 386

    name: tests (${{ matrix.os }}/go-${{ matrix.go_version }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-go@v2.1.5
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@v2.4.0

      - name: run-tests-race
        if: ${{ matrix.arch == 'amd64' }}
        env:
          GOARCH: "${{ matrix.arch }}"
        run: go test -race -vet all -mod readonly ./...

      - name: run-tests
        if: ${{ matrix.arch == '386' }}
        env:
          GOARCH: "${{ matrix.arch }}"
        run: go test -vet all -mod readonly ./...

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: golangci/golangci-lint-action@v2.5.2

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.5
        id: go
        with:
          stable: false
          go-version: 1.17

      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@master

      - name: get staticcheck version
        id: get-staticcheck-version
        run: |
          echo "::set-output name=version::$(staticcheck --version | sed -e 's/,//g')"

      - name: staticcheck cache
        id: staticcheck-cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/staticcheck
          key: "${{ steps.get-staticcheck-version.outputs.version }}"

      - uses: actions/checkout@v2.4.0

      - name: run staticcheck
        run: |
          staticcheck ./...

  test-examples:
    strategy:
      matrix:
        include:
          - lang: python
            docker-image: python
          - lang: node
            docker-image: node:14-alpine
          - lang: go
            docker-image: golang:alpine
          - lang: dotnet
            docker-image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
          - lang: scala
            docker-image: mozilla/sbt

    name: test-examples (${{ matrix.lang }})
    runs-on: ubuntu-latest
    needs:
      - lint
      - staticcheck
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-go@v2.1.5
        id: go
        with:
          go-version: 1.17

      - name: go-build
        run: go build -o fake-gcs-server
        env:
          CGO_ENABLED: 0

      - name: sanity-check
        uses: docker://alpine
        with:
          entrypoint: sh
          args: -c "./fake-gcs-server -h"

      - name: docker pull image
        run: docker pull ${DOCKER_IMAGE}
        env:
          DOCKER_IMAGE: ${{ matrix.docker-image }}

      - name: test-${{ matrix.lang }}-example
        run: |
          docker run --entrypoint /bin/sh ${DOCKER_IMAGE} ci/run-${LANG}-example.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker-image }}
          LANG: ${{ matrix.lang }}

  unblock-pr:
    name: unblock-pr
    runs-on: ubuntu-latest
    needs:
      - test-examples
      - test
    steps:
      - run: "true"
